import { Platform, PlatformConfig } from "../types";

export const PLATFORMS: Record<Platform, PlatformConfig> = {
  instagram: {
    id: "instagram",
    name: "Instagram",
    shortName: "IG",
    handlePrefix: "@",
    color: "#E1306C",
    bgGradient: "from-[#833ab4] via-[#fd1d1d] to-[#fcb045]",
    icon: "Instagram",
    maxCharacters: 2200,
    maxHashtags: 30,
    supportsMedia: ["image", "video", "carousel"],
    aspectRatios: ["1:1 (Square)", "4:5 (Portrait)", "9:16 (Reels)"],
    features: {
      firstComment: true,
      thread: false,
      title: false,
      altText: true,
    },
  },
  tiktok: {
    id: "tiktok",
    name: "TikTok",
    shortName: "TT",
    handlePrefix: "@",
    color: "#00F2FE",
    bgGradient: "from-[#00f2fe] to-[#fe2c55]",
    icon: "Video",
    maxCharacters: 2200,
    maxHashtags: 20,
    supportsMedia: ["video"],
    aspectRatios: ["9:16 (Vertical Video)"],
    features: {
      firstComment: false,
      thread: false,
      title: false,
      altText: false,
    },
  },
  twitter: {
    id: "twitter",
    name: "X (Twitter)",
    shortName: "X",
    handlePrefix: "@",
    color: "#0F1419",
    bgGradient: "from-[#1DA1F2] to-[#0d8bd9]",
    icon: "Twitter",
    maxCharacters: 280,
    maxHashtags: 5,
    supportsMedia: ["image", "video", "text"],
    aspectRatios: ["16:9 (Landscape)", "1:1 (Square)", "4:5 (Portrait)"],
    features: {
      firstComment: false,
      thread: true,
      title: false,
      altText: true,
    },
  },
  linkedin: {
    id: "linkedin",
    name: "LinkedIn",
    shortName: "IN",
    handlePrefix: "@",
    color: "#0A66C2",
    bgGradient: "from-[#0A66C2] to-[#004182]",
    icon: "Linkedin",
    maxCharacters: 3000,
    maxHashtags: 5,
    supportsMedia: ["image", "video", "carousel", "text"],
    aspectRatios: ["1:1 (Square)", "16:9 (Landscape)", "4:5 (Document)"],
    features: {
      firstComment: true,
      thread: false,
      title: true,
      altText: true,
    },
  },
  facebook: {
    id: "facebook",
    name: "Facebook",
    shortName: "FB",
    handlePrefix: "@",
    color: "#1877F2",
    bgGradient: "from-[#1877F2] to-[#0e5aae]",
    icon: "Facebook",
    maxCharacters: 63206,
    maxHashtags: 10,
    supportsMedia: ["image", "video", "carousel", "text"],
    aspectRatios: ["1:1 (Square)", "16:9 (Landscape)", "4:5 (Portrait)"],
    features: {
      firstComment: true,
      thread: false,
      title: false,
      altText: true,
    },
  },
  threads: {
    id: "threads",
    name: "Threads",
    shortName: "TH",
    handlePrefix: "@",
    color: "#000000",
    bgGradient: "from-[#101010] to-[#262626]",
    icon: "AtSign",
    maxCharacters: 500,
    maxHashtags: 5,
    supportsMedia: ["image", "video", "text"],
    aspectRatios: ["1:1 (Square)", "4:5 (Portrait)", "9:16 (Vertical)"],
    features: {
      firstComment: false,
      thread: true,
      title: false,
      altText: true,
    },
  },
  youtube: {
    id: "youtube",
    name: "YouTube Shorts",
    shortName: "YT",
    handlePrefix: "@",
    color: "#FF0000",
    bgGradient: "from-[#FF0000] to-[#cc0000]",
    icon: "Youtube",
    maxCharacters: 5000,
    maxHashtags: 15,
    supportsMedia: ["video"],
    aspectRatios: ["9:16 (Shorts)", "16:9 (Standard)"],
    features: {
      firstComment: true,
      thread: false,
      title: true,
      altText: false,
    },
  },
};

export const ALL_PLATFORMS: Platform[] = [
  "instagram",
  "tiktok",
  "twitter",
  "linkedin",
  "facebook",
  "threads",
  "youtube",
];
